// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mocks/mock_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	alldebrid "debrid-downloader/internal/alldebrid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAllDebridClient is a mock of AllDebridClient interface.
type MockAllDebridClient struct {
	ctrl     *gomock.Controller
	recorder *MockAllDebridClientMockRecorder
	isgomock struct{}
}

// MockAllDebridClientMockRecorder is the mock recorder for MockAllDebridClient.
type MockAllDebridClientMockRecorder struct {
	mock *MockAllDebridClient
}

// NewMockAllDebridClient creates a new mock instance.
func NewMockAllDebridClient(ctrl *gomock.Controller) *MockAllDebridClient {
	mock := &MockAllDebridClient{ctrl: ctrl}
	mock.recorder = &MockAllDebridClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllDebridClient) EXPECT() *MockAllDebridClientMockRecorder {
	return m.recorder
}

// CheckAPIKey mocks base method.
func (m *MockAllDebridClient) CheckAPIKey(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAPIKey", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAPIKey indicates an expected call of CheckAPIKey.
func (mr *MockAllDebridClientMockRecorder) CheckAPIKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAPIKey", reflect.TypeOf((*MockAllDebridClient)(nil).CheckAPIKey), ctx)
}

// UnrestrictLink mocks base method.
func (m *MockAllDebridClient) UnrestrictLink(ctx context.Context, link string) (*alldebrid.UnrestrictResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnrestrictLink", ctx, link)
	ret0, _ := ret[0].(*alldebrid.UnrestrictResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnrestrictLink indicates an expected call of UnrestrictLink.
func (mr *MockAllDebridClientMockRecorder) UnrestrictLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnrestrictLink", reflect.TypeOf((*MockAllDebridClient)(nil).UnrestrictLink), ctx, link)
}
